# This file generated by Quarto; do not edit by hand.
# shiny_mode: core

from __future__ import annotations

from pathlib import Path
from shiny import App, Inputs, Outputs, Session, ui




def server(input: Inputs, output: Outputs, session: Session) -> None:
    import seaborn as sns
    penguins = sns.load_dataset("penguins")

    # ========================================================================

    from shiny.express import render, ui

    ui.input_select("x",
                    "Variable:",
                    choices=["bill_length_mm", "bill_depth_mm"])

    ui.input_select("dist", 
                    "Distribution:", 
                    choices=["hist", "kde"])

    ui.input_checkbox("rug",
                      "Show rug marks", 
                      value = False)

    # ========================================================================

    @render.plot
    def displot():
        sns.displot(
            data=penguins, 
            hue="species",
            multiple="stack",
            x=input.x(),
            rug=input.rug(),
            kind=input.dist())

    # ========================================================================



    return None


_static_assets = ["shiny-dashboard_files","dashboard-prac\\shiny-dashboard_files\\libs\\quarto-html\\tippy.css","dashboard-prac\\shiny-dashboard_files\\libs\\quarto-html\\quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css","dashboard-prac\\shiny-dashboard_files\\libs\\bootstrap\\bootstrap-icons.css","dashboard-prac\\shiny-dashboard_files\\libs\\bootstrap\\bootstrap-f9c3a980a829ab9d6a74b295b7269fb0.min.css","dashboard-prac\\shiny-dashboard_files\\libs\\quarto-dashboard\\datatables.min.css","dashboard-prac\\shiny-dashboard_files\\libs\\clipboard\\clipboard.min.js","dashboard-prac\\shiny-dashboard_files\\libs\\quarto-html\\quarto.js","dashboard-prac\\shiny-dashboard_files\\libs\\quarto-html\\popper.min.js","dashboard-prac\\shiny-dashboard_files\\libs\\quarto-html\\tippy.umd.min.js","dashboard-prac\\shiny-dashboard_files\\libs\\quarto-html\\anchor.min.js","dashboard-prac\\shiny-dashboard_files\\libs\\bootstrap\\bootstrap.min.js","dashboard-prac\\shiny-dashboard_files\\libs\\quarto-dashboard\\quarto-dashboard.js","dashboard-prac\\shiny-dashboard_files\\libs\\quarto-dashboard\\stickythead.js","dashboard-prac\\shiny-dashboard_files\\libs\\quarto-dashboard\\datatables.min.js","dashboard-prac\\shiny-dashboard_files\\libs\\quarto-dashboard\\pdfmake.min.js","dashboard-prac\\shiny-dashboard_files\\libs\\quarto-dashboard\\vfs_fonts.js","dashboard-prac\\shiny-dashboard_files\\libs\\quarto-dashboard\\web-components.js","dashboard-prac\\shiny-dashboard_files\\libs\\quarto-dashboard\\components.js"]
_static_assets = {"/" + sa: Path(__file__).parent / sa for sa in _static_assets}

app = App(
    Path(__file__).parent / "shiny-dashboard.html",
    server,
    static_assets=_static_assets,
)
